apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    app: frontend
spec:
  containers:
  - name: app-pod
    image: nginx
  - name: sidecar-pod
    image: alpine
    command: ["sh", "-c", "sleep 30"]
  restartPolicy: Never
